"""Add encryption_key to Config and create Connection model

Revision ID: 06f74ddfcc29
Revises: efc16d33a348
Create Date: 2025-12-21 18:42:17.147351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f74ddfcc29'
down_revision = 'efc16d33a348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_key', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('encryption_key')

    # ### end Alembic commands ###
