"""Add rating and usage tracking fields to connections

Revision ID: 985c025b7396
Revises: 06f74ddfcc29
Create Date: 2025-12-27 01:45:42.072308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985c025b7396'
down_revision = '06f74ddfcc29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_up', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rating_down', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('usage_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_column('usage_count')
        batch_op.drop_column('rating_down')
        batch_op.drop_column('rating_up')

    # ### end Alembic commands ###
