"""Fix user status default value

Revision ID: 9bfea6e8348c
Revises: e997f190d7fb
Create Date: 2025-10-30 22:29:46.174167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfea6e8348c'
down_revision = 'e997f190d7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE users SET status = 'NEW' WHERE status IS NULL")

    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('status',
                   existing_type=sa.String(length=20),
                   nullable=False,
                   server_default='NEW')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('status',
                   existing_type=sa.String(length=20),
                   nullable=True,
                   server_default=None)

    # ### end Alembic commands ###
