"""Add author_id, created_at, updated_at to memos

Revision ID: e997f190d7fb
Revises: fc42d30f7165
Create Date: 2025-10-28 00:48:12.860327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e997f190d7fb'
down_revision = 'fc42d30f7165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True, server_default='1'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_memos_category'))
        batch_op.drop_index(batch_op.f('idx_memos_type'))
        batch_op.create_index('idx_memos_author_id', ['author_id'], unique=False)
        batch_op.create_index('idx_memos_category_id', ['category_id'], unique=False)
        batch_op.create_index('idx_memos_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_memos_type_id', ['type_id'], unique=False)
        batch_op.create_foreign_key('fk_memos_author_id', 'users', ['author_id'], ['id'])

    with op.batch_alter_table('memos') as batch_op:
        batch_op.alter_column('author_id', nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_memos_author_id', type_='foreignkey')
        batch_op.drop_index('idx_memos_type_id')
        batch_op.drop_index('idx_memos_created_at')
        batch_op.drop_index('idx_memos_category_id')
        batch_op.drop_index('idx_memos_author_id')
        batch_op.create_index(batch_op.f('idx_memos_type'), ['type_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_memos_category'), ['category_id'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
